anneal_para_ts_nompi: anneal_para_ts_nompi.o
	$(CXX) -o anneal_para_ts_nompi anneal_para_ts_nompi.o

anneal_para_ts_nompi.o:
	$(CXX) -I/usr/local/include \
		-o anneal_para_ts_nompi.o -c anneal_para_ts.cpp

clean:
	rm *.o anneal_para_ts_nompi
